services:
  api:
    build: .
    container_name: banking_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      SERVICE_NAME: gateway-api
      # Opcional: setear commit en runtime (si quieres)
      # GIT_SHA: "local"
    volumes:
      - .:/app
      - /app/node_modules
