services:
  api:
    build: .
    container_name: banking_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      SERVICE_NAME: gateway-api
      DATABASE_URL: postgres://app:app@db:5432/social
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: banking_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: